jordansissel/fpm

README.md

I think this one's fairly self-explanatory, but it should save mac users a few minutes of googling around.

Adding guntar installation note for OS X

---

lib/fpm/package/dir.rb

From http://ruby-doc.org/stdlib-2.2.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-copy_entry:
```
Both of src and dest must be a path name. src must exist, dest must not exist.
```
(tested & working)

symlinks need full dest path for FileUtils.copy_entry

---

lib/fpm/package/python.rb

Here's a PR for changing the default PyPi base URL for --python-pypi. I've tested this with both `pip` and `easy_install` on OS X.
Thanks for FPM!

Default to HTTPS for --python-pypi URL

---

templates/deb/postinst_upgrade.sh.erb
templates/deb/postrm_upgrade.sh.erb
templates/deb/preinst_upgrade.sh.erb
templates/deb/prerm_upgrade.sh.erb

These templates are only used when --before-upgrade and --after-upgrade are used.

Fix up debian maintenance script templates

---

templates/deb/postinst_upgrade.sh.erb
templates/deb/postrm_upgrade.sh.erb

This further improves the postinstall and preremoval scripts' correctness for debian packages when `--*-upgrade` arguments are used. See #661

Add improved abort-install and abort-remove

---

lib/fpm/package/python.rb

See https://github.com/jordansissel/fpm/issues/587.
When using fpm to package python modules using pip, we need to avoid "wheel" format until it is explicitly supported.

Until python wheel format is supported, tell pip to --no-use-wheel

---

templates/rpm.erb

Fixes https://github.com/jordansissel/fpm/issues/803

Second %pre should be %post

---

spec/fpm/package/deb_spec.rb

lintian expects the package name to ends with ".deb". Also, rspec
disallows the use of a let variable in an `after(:context)` hook. Also
fix the name of instance variable `@staging_path`.

rspec: fix lintian test

---

lib/fpm/command.rb

Works like a series of `--exclude`s; sort of a counterpart to --include.
The rationale is to allow a file under developer control to specify exclusion patterns separate from fpm execution, which is under CI control (in our world).

Add command line flag for --exclude-file.

---

lib/fpm/command.rb

When I first started using `fpm`, I was confused about what package types I could use to make rpm packages or debian packages from. I think it would go a long way to help beginners if we listed the types of packages that `fpm` works with.
This pull request just lists the package types that `fpm` works with. Not strictly necessary, but I think it's a good idea.
Comes pre-tested. :+1:

List loaded package types on the help screen

---

README.md

Rename link title (jira -> github).

Fixed github link title in RAEDME

---

lib/fpm/package/deb.rb
spec/fpm/package/deb_spec.rb

When building Debian packages with debhelper, files in `/etc` are
automatically marked as configuration files (this is done since
compatibility level 3 which was introduced in 2000). Therefore, packages
built with fpm may come as a surprise since they don't do that. A user
can still add `--config-files /etc` but they have to know that (usually
after a valuable modification has been erased).
This change add `/etc` to the list of configuration files for Debian
unless fpm is invoked with `--no-config-files`.
Closes: #873 
Unlike what I was told in #873, I didn't add any warning for the behavior change. How should I add that?

For Debian packages, register files in `/etc` as conf files

---

templates/rpm.erb

This goes back to #875 . It makes sure that no-op scripts put into the templated version of removal scripts in the case of a `--*-upgrade` option doesn't explode. Tested :+1:

Add `:` to pre- and post- removal scripts to make them safer

---

lib/fpm/package/sh.rb
templates/sh.erb

This adds `--before-install` functionality to the `sh` output target. It runs the `--before-install` script as part of the BASH script that is run before the tarball is extracted. Tested :+1:

Feature: sh before-install script

---

lib/fpm/package/empty.rb
lib/fpm/package/tar.rb
spec/fpm/package/empty_spec.rb

I think it is useful to have `empty` as an output target. Sometimes, when converting from a certain package type to another, there is a problem with how the conversion takes place. I want to be able to run fpm with `--debug-workspace` and see what the result of converting from the source type, without regard to the target type until I've worked out what went wrong converting the source type. I don't care what type of package it outputs. In this case, having an `empty` output target is nice.
PR comes pre-tested, and includes a unit test for the `#to_s` function used to make `empty` an output target.

Feature: empty output package target

---

lib/fpm/package/sh.rb
spec/fpm/package/sh_spec.rb
templates/sh.erb

We're starting to use the SH package format for a number of different project types. As part of this, we're adding some metadata to the packages so that we can easily determine how to deploy them. For example, a Rails project will want to roll unicorns, but a package of JavaScript assets would be installed differently. For other users, this is a no-op, with the exception of seeing a new `__METADATA__` line in the file, just prior to the `__ARCHIVE__` line.
@jordansissel

Add package metadata to slug file format

---

lib/fpm/package/python.rb
spec/fixtures/python/setup.py
spec/fpm/package/python_spec.rb

This is useful for example in the case of a dependency on the python
PyYAML package.
By default, this dependency gets translated to a debian package
dependency on python-pyyaml. That package does not exist on Debian
systems (it is called python-yaml), so a way to override the dependency is needed.
A similar option exists already for gems (--gem-disable-dependency).

Add --python-disable-dependency option to disable specific python dependencies

---

lib/fpm/package/pyfpm/get_metadata.py

This is a fix for unittest2, as it's [setup.py](https://hg.python.org/unittest2/file/bfdcdc6bdb89/setup.py#l13) passes a non-string parameter for `version` into `setup()`. Trying to package it with fpm results in this nastiness:
`fpm -s python -t rpm --debug  unittest2`
```
...
running get_metadata {:line=>"46", :file=>"cabin/mixins/pipe.rb", :level=>:info}
Traceback (most recent call last): {:line=>"46", :file=>"cabin/mixins/pipe.rb", :level=>:info}
File "setup.py", line 87, in <module> {:line=>"46", :file=>"cabin/mixins/pipe.rb", :level=>:info}
setup(**params) {:line=>"46", :file=>"cabin/mixins/pipe.rb", :level=>:info}
File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup {:line=>"46", :file=>"cabin/mixins/pipe.rb", :level=>:info}
dist.run_commands() {:line=>"46", …
```

pyfpm: Fall back to __str__ when encoding package metadata as JSON

---

lib/fpm/package/deb.rb

Hello, this change prevents `lintian` (and therefore Ubuntu Package Manager) generating the
```
control-file-has-bad-permissions shlibs 0664 != 0644
````
error and the subsequent "violates the quality standards" alert when the `--deb-shlibs` option is used.
Originally discovered via https://github.com/dimensio/libpng16-deb/issues/1

Ensure --deb-shlibs file permission to keep lintian happy

---

lib/fpm/package.rb
lib/fpm/package/rpm.rb
spec/fpm/package/rpm_spec.rb
templates/rpm.erb

When --rpm-dist is specified, pass the dist tag to rpmbuild and
correctly name the file to ensure packages can be built with a
specific distribution in mind.

Support RPM dist tag

---

fpm.gemspec

and .reject seems to came from insist 0.0.6
but work with 1.0.0 as well
the error i was getting was:
```
1) FPM::Package::Deb#output when the deb's control section is extracted should have the requested triggers in the triggers file
Failure/Error: reject { triggers =~ /^interest from-meta-file$/ }.nil?
NoMethodError:
undefined method `reject' for #<RSpec::Core::ExampleGroup::Nested_3::Nested_8::Nested_1:0x00000001b13248>
```

rspec tests use .reject

---

lib/fpm/command.rb

The help currently displays a line break instead of a literal \n, this replaces \n with \\n.

Update --description in help to display a literal \n instead of a newline

---

lib/fpm/package/virtualenv.rb

Add support for URLs passed to pip with pypi --extra-index-url, so you can include code from both public & private PyPi repos.

add support for pypi --extra-index-url

---

lib/fpm/util.rb

The FreeBSD version of tar doesn't include the options --owner and
--group among others. Instead change to use gnutar as the default.
This adds a dependency of installing
https://freshports.org/archivers/gtar/ for anyone creating packages
under FreeBSD (similar to doing brew install gnu-tar under OSX)

Change FreeBSD to use gtar

---

lib/fpm/package/rpm.rb

adds comment in code how the fpm triggers are mapped to rpm names
as it's not document anywhere of the mapping, and coming from rpm world it's hard to understand what fpm names mean.

add rpm internal names as comments

---

lib/fpm/package/cpan.rb

I just removed the unused switch --cpan-local-module and install package if it's file or directory.

Install local module if package is file

---

lib/fpm/command.rb
lib/fpm/package.rb

`--exclude-file` doesn't work due to a variable error on L367

Fix broken behaviour in --excludes-file option

---

lib/fpm/package/dir.rb

Per the [source for ::Dir.tmpdir](http://ruby-doc.org/stdlib-1.9.3/libdoc/tmpdir/rdoc/Dir.html#method-c-tmpdir), these are the actual environment variables that should be checked:
```
for dir in [ENV['TMPDIR'], ENV['TMP'], ENV['TEMP'], @@systmpdir, '/tmp']
```

Clarified tempdir error message

---

lib/fpm/command.rb

Allow arguments in .fpm files, old behaviour put those arguments in the middle of the command line, and further options were not recognized. Fix issue #976
Also, add optional default arguments handling from the FPMOPTS environment variable. This allows default arguments to be specified in regard to the .fpm file. This could be useful for a build bot that can specify a default version number (git revision) in case the .fpm file doesn't specify it.

.fpm parsing: separate options and arguments and add FPMOPTS handling

---

lib/fpm/package/rpm.rb
templates/rpm.erb

This can be useful to have requirements for different stages.
Examples:
--rpm-add-require 'Requires(post): /usr/sbin/alternatives'
--rpm-add-require 'Requires(preun): /usr/sbin/alternatives'

rpm: Add a option to insert raw Require statements

---

fpm.gemspec
lib/fpm/rake_task.rb
spec/fpm/rake_task_spec.rb

This allows you to easily use `fpm` in a Rakefile without a bunch of backticks or other non-Ruby ugliness. For example, given a Rakefile:
```ruby
require "fpm/rake_task"
FPM::RakeTask.new(:awesome_pkg, :source => :dir, :target => :tar) do |pkg|
pkg.args = %w(bin/)
pkg.verbose = true
pkg.config_files = %w(foo bar)
end
```
Run `rake awesome_pkg`:
```
Created package {:path=>"awesome_pkg.tar"}
```

Add RakeTask

---

lib/fpm/package/rpm.rb

Fix file names with closing braces in their name.

---

lib/fpm/command.rb

Add (hopefully) more clear description of _'--directories'_ option, when it should be used multiple times if directories are not under same parent directory. Current explanation is not very clear about this, and it seems there are no other usage examples with _'--directories'_ option in fpm project' wiki, I think it is a good idea to explain it in this place.

Add more clear description of --directories option

---

lib/fpm/package/cpan.rb

This is useful in case the user doesn't care wether or not some test fails

Add --[no-]cpan-cpanm-force flag to allow passing --force to cpanm

---

lib/fpm/package/deb.rb

According to debian systemd packaging guide (https://wiki.debian.org/Teams/pkg-systemd/Packaging#systemd_unit_files_naming_and_installation), distributed systemd unit files must be located in "/lib/systemd/system", and not "/etc/systemd/system"

Follow debian systemd packaging guide

---

lib/fpm/package/deb.rb

Oh god, sorry, i did'nt see that systemd unit files are handled two times !
(See: https://github.com/jordansissel/fpm/pull/1040)
If i don't replace this path too, unit files are presents 2 times in the debian package, first in /lib/systemd, second in /etc/systemd
Btw, i suspect another bug, that's a strange behaviour, don't you think ?

Follow debian systemd packaging guide #2

---

lib/fpm/command.rb

Current handling of option --description does not accept a description 'value' anymore as former commit 52ac00b5b3f7bc56c13ea0a57d8af609f1075b18 seems to be incomplete.

Fix parsing of --description

---

lib/fpm/package/deb.rb
lib/fpm/package/dir.rb

This removes some lintian non-standard-dir-perm warnings and moves output
deb packages slightly closer to Debian policy compliance.

deb: Create directories as 0755 as per Debian policy

---

README.md

This removes a slightly confusing bit of information from the readme that no longer looks relevant.
I think this is a result of the work done in 7ced849. The package name "awesome" was removed from the example `fpm` command in the readme, but the leading paragraph was not updated.

Remove artifact of old code in README

---

lib/fpm/command.rb

The help output for --prefix states:
> A path to prefix files with when building the target package. This may be necessary for all input packages. For example, the 'gem' type will prefix with your gem directory automatically.
This should probably be:
> A path to prefix files with when building the target package. This may **not** be necessary for all input packages. For example, the 'gem' type will prefix with your gem directory automatically.

Fix for --help output

---

README.md

This is needed or many tests fail on Ubuntu since bsdtar isn't there by default. 9 tests fail on Ubuntu 15.10 even after that but much less with bsdtar installed.
PS: Cleaned up some whitespace too

Added bsdtar installation instructions in README

---

lib/fpm/package.rb
lib/fpm/package/deb.rb
lib/fpm/package/freebsd.rb
lib/fpm/package/osxpkg.rb
lib/fpm/package/pacman.rb
lib/fpm/package/rpm.rb

The main issue that this patch tries to address it that ``freebsd`` packager ignored ``--package`` CLI option. Working on it I also decided to add some customization points to ``FPM::Package#to_s`` such that subclasses can easily overload certain bits of its behavior.

fixes for FPM::Package#to_s and relatives

---

lib/fpm/package/gem.rb

Without `--no-user-install`, the gem command fails with:
ERROR:  User --install-dir or --user-install but not both
Apparently, on some circumstances, gem can default to a user install and prevent it from using `--install-dir`.
I am using gem 2.5.1 on ruby 2.3.0p0 (2015-12-25 revision 53290)

Fix gem error

---

lib/fpm/util.rb
spec/fixtures/python/easy_install_default.py
spec/fpm/package/python_spec.rb

Created mainly to fix the issue spotted [here](https://github.com/jordansissel/fpm/commit/42df3cccc0a6cb7fc92ab026d57db938e731fbe4#commitcomment-17079001).

add FPM::Util.execmd and fix python_spec.rb

---

lib/fpm/rake_task.rb

The rake task class needs to require the fpm namespace in order
to be included elsewhere.

Add fpm namespace require for rake task

---

lib/fpm/rake_task.rb

Exiting after fpm success means that further rake tasks fail to execute,
and Rake simply exits. Instead, only abort if the fpm exits non-zero

Rake task should not exit if successful

---

fpm.gemspec
lib/fpm/package/freebsd.rb
lib/fpm/util.rb
lib/fpm/util/tar_writer.rb

Fixes #1107. I had to provide new class ``FPM::Util::TarWriter`` to patch problems with ``Gem::Package::TarWriter``. Refinemends didn't seem to be useful in this case so I decided to get rid of the only refinement used in ``freebsd.rb``, as well as to remove the dependency of ``corefines``.
Tested on FreeBSD 10.3 (used to succesfully build [vagrant-installers](https://github.com/mitchellh/vagrant-installers)).
BTW. Is it possible to have fpm-1.5.1 with this PR included soon?

workaround rubygems issue #1608 and remove dependency of corefines

---

fpm.gemspec
lib/fpm/command.rb
lib/fpm/package/dir.rb
lib/fpm/package/pleaserun.rb
lib/fpm/package/tar.rb
spec/acceptance/puppet/manifests/install.pp
spec/acceptance/puppet/manifests/remove.pp
spec/fpm/package/rpm_spec.rb
templates/pleaserun/generate-cleanup.sh
templates/pleaserun/install-path.sh
templates/pleaserun/install.sh
templates/pleaserun/scripts/after-install.sh
templates/pleaserun/scripts/before-remove.sh

The `pleaserun` tool helps generate service manifests for different service platforms such as systemd and runit.
This PR introduces `pleaserun` as a package source. The goal is to have a package you can install that will "do the right thing" and install the best-fitting service manifest for the target system.
Example usage:
```
% fpm -s pleaserun -t rpm -a all -n redis-service --pleaserun-name redis /usr/bin/redis-server
...
% sudo yum install redis-service-1.0-1.noarch.rpm
...
Installing  : redis-service-1.0-1.noarch                                                            1/1
Platform systemd (default) detected. Installing service.
To start this service, use: systemctl start redis
Verifying   : redis-service-1.0-1.noarch                                                            1/1 …
```

New source: pleaserun

---

lib/fpm/rake_task.rb

last_comment is deprecated with Rake 11.1.0 and will be removed with Rake 12.
more info read:
https://github.com/ruby/rake/issues/116

last_comment is depricated replaced with last_description

---

templates/rpm.erb

The `--rpm-tag` option was ignored when used on command line.

Fix for ignoring --rpm-tag option on command line

---

lib/fpm/package/rpm.rb
spec/fpm/package/rpm_spec.rb
templates/rpm.erb

This is a new version of PR https://github.com/jordansissel/fpm/issues/820 by @dhajoshi. It fixes rpm-builds breaking, when `--prefix` ends with a slash. Comes with tests included. Details about the problem can be found in issue #819.
In case there are any questions, please feel free to ask them. If you want anything changed about this PR, please just let me know and I'll get it done. Thank you.

remove trailing slash from --prefix option in rpm-packages, fixes #819

---

fpm.gemspec

json 2.0.1 was published today and requires ruby's version
to be greater than 2.0.

prevents json dependency from creeping to version 2.0

---

lib/fpm/package/gem.rb
spec/fpm/package/gem_spec.rb

This makes it possible to create packages from gems for ruby versions
which are not currently installed on the machine you build the package on.
Tests are included.

gem: make it posssible to set the shebang

---

lib/fpm/package.rb
spec/fpm/package_spec.rb

This PR uses `Stud::Temporary.directory` instead of `::Dir.mktmpdir` to generate temporary directories for the "build"- and "staging"-dirs. This means that both directories now respect the `--workdir`-argument. Further details on this issue can be found in #1124.
In case there are any questions, please feel free to ask them. If you want anything changed about this PR, please just let me know and I'll get it done. Thank you.

fix --workdir not having an effect on the build and staging dirs, fixes #1124

---

lib/fpm/package/pacman.rb

Fixes #1153.
This is based on https://wiki.archlinux.org/index.php/PKGBUILD#Dependencies which allows either '+', '.', '@' and '_' in either the package name or the version.

Fix pacman dependency regex.

---

lib/fpm/package/cpan.rb

Version 2 of the CPAN metadata specification uses 'prereqs' for dependencies rather than 'requires'. This patch handles both.

Fix #1114 by looking for new-style keys in CPAN metadata

---

lib/fpm/package/cpan.rb

@liger1978
`.packlist` files are useless junk containing irrelevant build information. In `noarch` packages they end up being the only file in the `lib64` directory when converting to e.g. RPMs (breaking the standard for `noarch` packages). This patch removes them from the package and also removes all empty parent directories of the unlinked `.packlist` file resulting in no more pollution of the `lib64` directory on the target system.
This is the second iteration of this patch after further testing.  This version breaks out of the `do` loop when a non-empty directory is found (more efficient) and sorts the directory contents before comparison to find empty dirs (annoyingly some platforms list contents as `[".", ".."]` and others as `["..", '.']`).

Fix #1179 Remove .packlist files and empty parent directories from CPAN packages

---

lib/fpm/command.rb
spec/fpm/command_spec.rb

The flags for chdir, input, and output aren't immediately intuitive as to what they're short for. This commit adds long versions and a spec stub for chdir. Resolves #1187.

Add long flag options for chdir, input, and output

---

README.md

If you try to create a rpm from a tar file you get: 
"Need executable 'rpmbuild' to convert tar to rpm {:level=>:error}"
Just pull the dependencies

Install rpm-build dependencies

---

lib/fpm/package/freebsd.rb

Alternative implementation of #1140. I'm not super happy with the way the casing works but I think this can extend to cover platforms like ARM, MIPS, SPARC, etc down the track. There is a pseudo-authoritative list of valid architecture and wordsize options [here](https://github.com/freebsd/pkg/blob/203e665dcff3d669cbcc6fc26a44323d1fddd958/libpkg/private/elf_tables.h#L83) but I've only really kept the x86 parts of it. Since i386 and x86_64 both use the same architecture (x86), I've just set this as is for now.
Overall I feel like this implementation is ugly but I can't think of a nicer way to do it. This is at least more consistent with what the other package architecture mutators do, like for RPM or Deb.

Use global architecture switch for FreeBSD ABI

---

CONTRIBUTORS
lib/fpm/package/cpan.rb

(Also added myself to CONTRIBUTORS as I've done a few patches now)

Ensured result is not nil. Fixes #1202.

---

lib/fpm/package/cpan.rb

The new way of searching metacpan with an http `POST` consistently requires numerical version number (i.e. no `v` prefix).  This patch tested against 73 CPAN modules: https://gitlab.com/harbottle/epmel/builds/6722395

Fixes #1236 Fixed version number for metacpan search

---

lib/fpm/package/virtualenv.rb

this branch contains two improvements to allow using fpm to distribute end user python applications _and_ their dependencies together, in one virtualenv based package.

make virtualenv packages truly standalone

---

docs/installing.rst

The meta package is called `build-essential` not `build-essentials`.

docs/installing: Fix build deps on Debian-derived systems

---

.travis.yml

The test was failing because the calculated staging path is incorrect
with brew. If done in a virtualenv it is correct.

Fix OSX Python tests

---

lib/fpm/package/zip.rb

See https://github.com/jordansissel/fpm/issues/1313

Fix zipfile target.

---

lib/fpm/package/virtualenv.rb

"pip install" in addition to the --index-url and --extra-index-url
flags, offers the `--find-links` flag, which tells pip to parse
an html index document looking for wheel/egg/source files without
expecting the "simple" pypi layout or to look in a local directory
for package files.

Add --virtualenv-find-links flag

---

docs/installing.rst

For CentOS7, I needed to install rubygems.
Not sure if it is included in e.g. ruby-devel for previous versions?

Add rubygems to CentOS install line

---

.travis.yml

* Adds known-good Ruby minor versions to the `.travis.yml` file for 2.3.x and 2.4.x.
* The Travis checks in this PR will fail until #1264 is fixed. This is, literally, TDD.

Update Travis config with Ruby 2.3 and 2.4.

---

lib/fpm/package/cpan.rb

Note that this is the same comparison a few lines later (line 179).  Without this change, I would never get all the Perl modules aligned perfectly.  As far as I can determine, this is what CPAN is enforcing, anyway.

Be consistent in letting newer Perl module versions meet the requirement, if not otherwise specified

---

lib/fpm/package/cpan.rb

Support for v0 of the MetaCPAN API has been removed in the last few days, completely breaking `fpm`'s ability to package CPAN modules.  I'm new to both Ruby and this service, but a quick scanning of the docs and some other online resources led me to this relatively small change, which seems to work well to adjust to the new API.
Fixes #1336

Update to v1 of MetaCPAN API

---

lib/fpm/package/cpan.rb

This is how the version of those dependencies themselves are being provided.  I ran into this with Kafka::Librd and Alien::Librdkafka.  Removing this code allowed the versioning to be correctly checked.

Do not remove the leading "v" from version dependencies

---

lib/fpm/package/cpan.rb

This is a somewhat notable change to depend upon (and provide) Perl "capabilities" such as `perl(Capture::Tiny)`, instead of `perl-Capture-Tiny`.  Truthfully, I don't know how widespread this is, but it was absolutely _critical_ to get things running on my SLES system.  (Dealing with `Test2`, which presents itself as `Test-Simple`, which is also the name of a core module, was particulary problematic until I full switched over to dependencies)

Use capabilities in Perl dependencies

---

docs/use-cases/make-install.rst

Fixed markdown config to add text trailed by double colons to have the subsequent blocks correctly formatted as code.

Fixed markdown errors

---

lib/fpm/package/cpan.rb

Some CPAN modules have things like `use 5.008001`, which shows up in their dependencies.  However, that's not the version format used by the perl RPMs, which would be `5.8.1` (or newer).  This detects such situations and re-formats the version string.

Translate Perl version dependencies

---

docs/installing.rst

Add libffi-devel to fedora 23+ install step.

---

fpm.gemspec

`archive-tar-minitar` is not used on `fpm` and version 0.5.2, pinned on current version of `fpm`, has [vulnerabilities](https://github.com/atoulme/minitar/issues/5).

remove archive-tar-minitar as a dependency

---

docs/source/gem.rst
lib/fpm/command.rb
lib/fpm/package.rb
lib/fpm/package/deb.rb
lib/fpm/package/gem.rb
lib/fpm/util.rb
spec/fpm/package/deb_spec.rb
spec/fpm/package/gem_spec.rb
templates/deb/changelog.erb

Partial fix for https://github.com/jordansissel/fpm/issues/1232
Ready for review and merging.
It fetches the source epoch from the changelog for about a third of the gems I tried.
Native gems still have some randomness on Darwin, but I'm not going to worry about that;
docs/source/gem.rst mentions that it's only been verified to produce identical results on Linux.
The following test passes locally on ubuntu 16.04:
```
mkdir run1
ruby -Ilib bin/fpm -s gem -t deb --gem-stagingdir /tmp/gem1.tmp --source-date-epoch-from-changelog json
mv *.deb run1
mkdir run2
ruby -Ilib bin/fpm -s gem -t deb --gem-stagingdir /tmp/gem1.tmp --source-date-epoch-from-changelog json
mv *.deb run2
cmp run1/*.deb run2/*.deb
```

Implement reproducible gem -> deb conversion

---

fpm.gemspec

```
$ grep -r require.*stud .
./lib/fpm/package.rb:require "stud/temporary"
./spec/fpm/package/dir_spec.rb:require "stud/temporary"
./spec/fpm/package/deb_spec.rb:require "stud/temporary"
./spec/fpm/package/pacman_spec.rb:require "stud/temporary"
./spec/fpm/package/rpm_spec.rb:require "stud/temporary" # gem 'stud'
./spec/fpm/util_spec.rb:require "stud/temporary"
./spec/fpm/command_spec.rb:require "stud/temporary"
```
introduced to `lib/fpm/package.rb` in 4547540 via #1139 for #1124

spec: stud is runtime dependency

---

lib/fpm/package/dir.rb
spec/fpm/package/dir_spec.rb

Previously, if the symlink is included into the package and specified
with
my-sym-link.so=/usr/lib/my-sym-link.so
fpm would create directory, and put the
symlink inside `/usr/lib/my-sym-link.so/my-sym-link.so
which is very surprising and it doesn't follow the same
pattern as file copying is doing.

In case of a=b syntax where a is symlink, don't create directory

---

.travis.yml
lib/fpm/package.rb
lib/fpm/package/dir.rb
lib/fpm/package/tar.rb
spec/fpm/package/empty_spec.rb
spec/fpm/package/tar_spec.rb

(This is a rebase of #1302)
Fixes issue #1123 
Changes:
* Add spec for tar packages
* Use latest ruby version in Travis tests
* Disable OS X in Travis (a python test is broken)
* Refactor tar and dir packages to use a common script writer
* Do not create a .scripts directory if there are no scripts to be written
Please let me know if you don't want the Travis changes and I'll remove them from this PR.

Fix #1123 .script directory in tar

---

lib/fpm/package/apk.rb

This patch dramatically improves performance when building larger alpine apk packages.

Performance optimization for apk packages

---

docs/use-cases/make-install.rst

Two of the code blocks in the Node.js example were not being formatted as such.  This commit fixes that.

Correct formatting of commands in Node.js example

---

lib/fpm/package/deb.rb
templates/deb/postrm_upgrade.sh.erb

Makes Debian's `postrm purge` hook usable.
Adds a new CLI argument `--deb-after-remove-purge` and extends the already prepared (thanks a lot!) `postrm_upgrade.sh.erb` template.
Thanks for `fpm`!

Add --deb-after-purge FILE

---

lib/fpm/package/python.rb

Add --python-setup-py-arguments flag which can be used to pass arbitrary arguments to setup.py.

---

.gitignore
lib/fpm/package/rpm.rb

copy config files external to source

---

fpm.gemspec
lib/fpm/package/cpan.rb
lib/fpm/package/gem.rb

An option should be provided to include all gem dependencies when creating a package.  This is useful when creating a rubygem debian package that is "all inclusive".  You wouldn't have to create separate debian packages for each gem dependency.

Optionally allow gem dependencies to be installed

---

docs/source/dir.rst

Without this forward-slash, installing the resulting deb package can wipe out directories.

Add missing forward-slash to dir.rst

---

lib/fpm/package/rpm.rb

PR #1379/#860 introduced a new behavior for --config-files that fetches
config files from the local filesystem. The prior behavior was to
require these files to be provided by the source package (`--source`
flag).
This patch makes a hybrid solution which does, for any given
`--config-files foo` flag:
* does the path `foo` already exist in the staging area? Do nothing.
This means the package source (`-s gem` for example) provided this file.
* or, does the path `foo` exist in the local filesystem? If so, copy it
into the staging area.
* otherwise, consider this to be an error that the --config-files
setting cannot find the file, and fpm will fail with an error.

Restore prior --config-files behavior

---

lib/fpm/package/dir.rb
spec/fpm/package/dir_spec.rb

PR #1253, while fixed the bug where `source.link=dest/source.link`
resulted in `source.link=dest/source.link/source.link` introduced a bug
where `source=dest/` syntax stopped working for symlinks (it is ok for
files). This is now fixed, as the symlink source now behaves the same as
it would with a single file input. Test case testing this behaviour is
also added.
Fixes #1395

Allow source=dest/ syntax for symlinks

---

docs/use-cases/files.rst

Update the Jenkins/WAR example to use the more stable addresses, although they do redirect to mirrors and make the wget example output look nasty, it should be more reliable.

[Fixes #1402] Update files.rst

---

fpm.gemspec
lib/fpm/package.rb

Looking at the .travis.yml, it looks like you are supporting Ruby 1.9.3+.
Assuming this is correct, this PR:
1) specifies that in the gemspec
2) loads the backports that are still in use.
As I'm ready to publish a bunch of backports for Ruby 2.5, I'd like to deprecate the `require 'backports'` (which loads all of the backports). That was, in retrospect, not such a great idea as the number of backports is increasing with every Ruby version, and could potentially be an issue for some code. Moreover, it is wasteful to load the hundreds of backports when only a few are needed.
I wrote a script to run your test suite while making a list of the backports used. Assuming the coverage is good, there's only one used in the library.
Thanks

Require only the used backports

---

lib/fpm/package/rpm.rb

This change will allows the user to specify multi-threaded compression of RPMs.
RPM packaging can take a long time. Most of this time is the compression
of the rpm payload. Compression is compute heavy. But it can be speeded up 
if done on many cores in parallel rather than on a single core.
A 5Mb rpm I package takes 25 minutes using single threaded compression.
This goes down to 3 minutes when run multi-threaded.
Fixes https://github.com/jordansissel/fpm/issues/1419

add xzmt - multithreaded xz compression for rpmbuild [fixes #1419]

---

templates/rpm.erb

When using install command (from /usr/bin/install) in after_install
shell in creates a endless loop, because it jumps to funtion beginning
of install(). So it's best practise to rename it to _install() to avoid
collision with /usr/bin/install command

fix: install loop problem in rpm.erb

---

lib/fpm/package/deb.rb

This is a fix to correct a Issue I am running into (#1440) when creating deb packages with the config-files option.

Non ruby programmer attempt to fix config-file issue with deb packages

---

bin/fpm

Ruby 1.9 requires Rubygems internally and this is no longer strictly required. It's been this way since 2009, so it's a little hard to come by official documentation. I hope this works...
> Note: For Ruby 1.8 you must require 'rubygems' before requiring any gems.
http://guides.rubygems.org/rubygems-basics/#requiring-code

[Fixes #1397] It's no longer necessary to explicitly require 'rubygems'

---

lib/fpm/package/apk.rb

Alpine Linux describes the available control scripts at https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package.
This patch fixes an issue where `post-install` was registered multiple times, preventing `:after_install`, `:before_install`, `:before_upgrade`, and `:after_upgrade` from running the correct script if multiple options were declared.
The issue appeared in https://github.com/jordansissel/fpm/commit/87ce028644b0bb9913b00ccd814be58056d9c28f.

Fixes typo with APK control scripts

---

lib/fpm/package/deb.rb
templates/deb/deb.changes.erb

Issue #467 calls for creation of .debain.tar.gz, .dsc and .changes files.
This Patch adds generation of .changes file for Debian packages. 
.changes files (containing all files relevant to a package with their checksums) are used by some repository management tools when importing packages. 
Generating a .debian.tar.gz (which would contain the Debian specifics for this package, for example the rules file (basically, Makefile), the control file (specifying dependencies) and Debian specific patches) or a .dsc (which would specify the source package) might not be relevant for the use-case of fpm, though. 
Fixes #467.
The command line option --(no-)deb-generate-changes allows to select to generate the .changes file, the option --deb-dist allows to set a distribution (like sid) for the package.

Generate .changes file for Debian

---

lib/fpm/package/python.rb

python3 fix

---

Dockerfile

In order to follow best practice for Dockerfiles, this commit:
* Removes leading and trailing blank lines.
* Pins the base image to a specific version of Alpine; the latest, 3.7, is used.
* Tells `apk` to not cache any package lists.
* Puts each dependency on its own line.
* Does some minor reformatting for readability.

Dockerfile: Follow best practices

---

lib/fpm/package/cpan.rb

Perl modules have both META.json and META.yml. In the JSON, the perl
dependency appears as a string `"5.004"`, but in YAML it appears as a
number `5.004`! This may cause fpm to fail when trying to convert the
perl version into a dependency, so we now always treat the perl version
as a string.
Hopefully fixes #1514

Always treat perl dependency version as a string.

---

templates/deb/deb.changes.erb

Set the expected indentation format in changes according to the documentation: https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog

FIX: Proper indentation for changes

---

lib/fpm/package/rpm.rb

.pyc files must be newer-than (not equal-in-time-to) the .py file they come from. The copy_entry is dropping in time-equivalent files, so the resulting rpm has equivalent-timestamp files.   This leads to a pyc recompile by the first script invocation that has write perms to the .pyc file (probably root).
This could have unintended side effects, but I'm not seeing a more granular way to apply timestamp love to just .pyc files.

Preserve build-time timestamps when building rpms [#1538]

---

lib/fpm/package/deb.rb

If "--deb-templates" is used, fpm uses the wrong mode for this file. Since it is not an executable file, it should not have the executable bits set. The lintian tool complains (with an error) that the mode is incorrect, and that it should not be executable. Changing the mode to 0644 resolves this.

Changed the mode of templates file for deb packages to 0644

---

docs/installing.rst

Updated docs/installing.rst to reflect Oracle Enterprise Linux instructions since you have to install an Oracle repo before you can install ruby-devel.

Updated docs  to reflect Oracle Enteprise Linux instructions

---

fpm.gemspec

rubies >= 2.5 ship with JSON 2.x, so allowing bundler to resolve to newer
implementations eliminates conflicts with dependency trees that include JSON
2.x.
Breaking changes for JSON 2.x include removed support for older rubies [[1]],
so specifying in this manner ensures that older rubies can find 1.x, while
newer ones can resolve to 2.x
[1]: https://github.com/flori/json/blob/master/CHANGES.md#2015-09-11-200
Resolves: https://github.com/jordansissel/fpm/issues/1599

relax json dependency

---

lib/fpm/package/dir.rb

Calling Dir#input overwrote #license and #vendor with default values.
Thanks for FPM!

Dir#input: don't overwrite license and vendor

---

lib/fpm/package/deb.rb
templates/deb/postinst_upgrade.sh.erb
templates/deb/prerm_upgrade.sh.erb

Hi, this PR adds in two new options to enable/disable and autostart systemd services
`--[no-]deb-systemd-enable` to enable the systemd service after install
`--[no-]deb-systemd-auto-start` to auto start the service after install
Additionally, any service start/stop/restart will use the `deb-systemd-invoke` wrapper if installed on the system
This should solve https://github.com/jordansissel/fpm/issues/1363 and https://github.com/jordansissel/fpm/issues/1284
Even though you can now disable a service from starting by default, I think its important to still allow for using [deb-systemd-invoke](http://manpages.ubuntu.com/manpages/trusty/man1/deb-systemd-invoke.1p.html) to keep in line with debian standards.
Let me know if you need anything changed! Thanks :)

Allow auto-enable and auto-start for deb-systemd services after install

---

lib/fpm/package/deb.rb

The code specifies .gz when using non-gzip compression which breaks on recent debian packaging tools. Fixes #1647

Use variable instead of hardcoded filename

---

docs/installing.rst

The --no-ri and --no-rdoc switches have now been superseded by --no-document per https://guides.rubygems.org/command-reference/#gem_install

Update outdated "gem install" command

---

docs/installing.rst

Remove the additional repo that was added (because it's for developer previews aka betas for Oracle Linux and is unsupported) and enable the `ol7_optional_latest` repo instead (which is the fully supported repo for this stuff).  This ensures that supported packages are installed, including the `ruby-devel` package.
This also corrects the product name.
Signed-off-by: Avi Miller <avi.miller@oracle.com>

This improves the Oracle Linux install docs 

---

lib/fpm/package/rpm.rb
templates/rpm.erb

- spec file sections affected: %pre %post %preun %postun

rpm: add option to enable install-time macro expansion in scripts

---

docs/source/virtualenv.rst

This makes the "Example uses" heading a subsection of the virtualenv section.

virtualenv.rst: fix heading level

---

templates/sh.erb

This was nice performance improvement @jlogsdon made some time ago to a private fork.

Use head/tail over sed for metadata fetching in sh.erb template

---

lib/fpm/package/python.rb

instead of a space-separated argument string
Tested with this command:
bundle exec bin/fpm --debug -s python -t deb --python-pip =pip django
And verified that safesystem() to invoke pip is given a list.
Mentioned this here:
https://github.com/jordansissel/fpm/pull/1737#discussion_r560474705

Call safesystem() with a list

---

lib/fpm/package.rb
lib/fpm/package/apk.rb
lib/fpm/package/deb.rb
lib/fpm/package/dir.rb
lib/fpm/package/empty.rb
lib/fpm/package/freebsd.rb
lib/fpm/package/pacman.rb
lib/fpm/package/rpm.rb
lib/fpm/package/sh.rb
lib/fpm/package/tar.rb
lib/fpm/package/zip.rb
lib/fpm/util/tar_writer.rb
spec/fpm/package/pacman_spec.rb

Please consider this pull request. It fixes the backports error warning, as well as changes the compression standard for pacman to zsdt which is the current standard. The build still fails two test. One has to do with copy_entry preserve flag not working in Linux (at least on Arch). and the other has to do with python #! which I didn't mess with. 
Note I'm not all that familiar with ruby code so please take my edits with grain of salt.

backports and pacman errors fixed

---

docs/source/virtualenv.rst

Original `virtualenv-tools` causes issues when building Python3 virtual environments. Previously reported in #1491.

Update virtualenv documentation for Python3

---

fpm.gemspec

ffi 1.13 requires Ruby 2.3, which is not supplied by many still-supported distros (e.g Centos/RHEL 7), 1.12.X works there, so restrict to that.
Addresses #1708

Pin ffi to 1.12.x, for compatibility with Ruby 2.0

---

lib/fpm/package/deb.rb

If gem had a version constraint with just major version (e.g., ~>1),
the Debian packages were generated with wrong zero upper limit
(e.g., >= 1 and << 0). This results in unresolvable dependencies.

deb: Fixes gem pessimistic version constrains for single component versions

---

fpm.gemspec

Previously, rexml was included standard in Ruby. However, in 3.0.0, ruby
moved this library to be a "bundled gem", per the release notes:
https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
> The following default gems are now bundled gems.
> * rexml
Tested on Ruby 2.7.0 and 3.0.1 w/ bundler and it works.
```
% (rbenv shell 3.0.1; bundle install; bundle exec bin/fpm -s empty -t empty -n example)
% (rbenv shell 2.7.0; bundle install; bundle exec bin/fpm -s empty -t empty -n example)
```
Fixes #1793

Add rexml as dependency

---

lib/fpm/package/rpm.rb

[rpm] Escape single quotes in file names listed in `%files`

---

fpm.gemspec
lib/fpm/package/freebsd.rb
lib/fpm/util.rb
spec/fpm/package/cpan_spec.rb
spec/fpm/package/deb_spec.rb
spec/fpm/package/gem_spec.rb
spec/fpm/package/npm_spec.rb
spec/fpm/package/osxpkg_spec.rb
spec/fpm/package/pacman_spec.rb
spec/fpm/package/python_spec.rb
spec/fpm/package/rpm_spec.rb
spec/fpm/package/sh_spec.rb
spec/fpm/package/virtualenv_spec.rb

In this PR, the following changes shall occur:
Acceptance criteria: fpm can be installed without any `ffi` gem dependency.
Expected outcomes, all of the following:
* Ruby 2.0-2.2 shall be supported again? (Needs more research)
* New Apple M1 Macs shall be able to use fpm successfully.
* Newer Arch systems which ship only Ruby FFI 1.15 shall be able to use fpm successfully
This PR aims to address issues listed in #1795

Work in progress: Remove FFI as a dependency

---

templates/rpm.erb

The previous commit eats too much whitespace after the section headers
(`%pre`, `%post` etc.). There should remain a newline.
Correct versions (for `%pre`):
```
%pre
ugrade () {
```
and
```
%pre -e
upgrade() {
```
Without this patch, we get these (wrong):
```
%pre ugrade () {
```
and
```
%pre -e upgrade() {
```
(exact number of spaces can be different, but should not be relevant)
Fixes #1750
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>

Add back newlines after sections with macro expansion

---

docs/installing.rst

add 'brew install rpm' as a prerequisite in the OSX/macOS section

add 'brew install rpm' as a prerequisite in the OSX/macOS section

---

lib/fpm/package/deb.rb
spec/conversion/gem_to_deb.rb
spec/fpm/package/deb_spec.rb
spec/fpm/package/osxpkg_spec.rb
templates/deb.erb

(more history/research for this PR available in the parent issue #1788)
---
This fixes #1788. This also reverts #280. For #280, at the time, this
change to ignore versions was correct. Two years after #280, Debian
began allowing `Provides` field to have versions.
This change also fixes bug in gem-to-deb conversion where previously an
incorrect Provides syntax would be generated (but thanks to #280,
removed), so this bug was only noticed after #280 was undone!
Computers are hard sometimes.
Added tests for gem-to-deb conversion specifically for the Provides
field.
Tested manually with Docker on Ubuntu 14.04 and 18.04 and results meet
expectations.
The history here is follows:
* In 2012, fpm was patched to remove version specifiers in Provides
field because Debian didn't support it.
* In …

Allow versions in `Provides` field for Debian packages

---

lib/fpm/package/pyfpm/get_metadata.py

ex. 'charset_normalizer~=2.0.0; python_version >= "3"' is now included if the marker matches the build environment.

fixes #1307 - Also use setuptools' extras_require which contains complex dependencies

---

lib/fpm/package/freebsd.rb

This is a simple workaround, which transforms the filenames inside the
tar archive so that they start with `/`. This happens only in case
the filename doesn't begin with `+`, which is expected (or at least is
very likely) to be a metadata file.
```
$ tar --list -f test-package-0.0.1.txz
+COMPACT_MANIFEST
+MANIFEST
/etc/config
/usr/bin/script
$ pkg install -y test-package-0.0.1.txz && echo OK
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):
New packages to be INSTALLED:
test-package: 0.0.1
Number of packages to be installed: 1
[1/1] Installing test-package-0.0.1...
Extracting test-package-0.0.1: 100%
OK
```
Fixes #1811 …

FreeBSD package: Fix missing leading `/` in archive

---

lib/fpm/package/deb.rb
spec/fpm/package/deb_spec.rb

This resolves an issue caused by #1803 where a user was, historically, passing `--provides 'foo (<< 1.2.3)'` which was working correctly in prior versions of fpm but creating invalid Debian packages in the newer release.
This is a funny issue because previously fpm was removing the relationship text '(<< 1.2.3)' so it never made it into the resulting Debian package. Due to #1803, this text is now passed into the resulting package, and Debian package tooling rejects it.
Added tests to cover a few valid and invalid cases.
This change also adds code to validate other relationship fields (Depends, Suggests, etc) but does not actually do any validation.

Reject invalid Provides fields for Debian packages

---

lib/fpm/package/rpm.rb
spec/fpm/package/rpm_spec.rb

(note: fpm calls 'iteration' what rpm calls 'release')
rpmbuild will reject the `Release` tag containing a dash with the
following error (via fpm --verbose):
```
error: line 41: Illegal char '-' (0x2d) in: Release: 1-1 {:level=>:info}
Process failed: rpmbuild failed (exit code 1).
```
This patch copies the dash-to-underscore operation that is already
applied to the version field.
Adds tests for both iteration and version field.
Fixes: #1833

rpm: Replace dash with underscore.

---

spec/fpm/package/freebsd_spec.rb

- Files in the tarball should begin with / (#1811, #1844)
- Assert certain top-level manifest fields
- Assert manifest files are present
Idea from #1844

Add tests for FreeBSD packages.

---

.readthedocs.yaml
docs/requirements.txt

https://blog.readthedocs.com/build-errors-docutils-0-18/
For #1848
Hoping this fixes it. Readthedocs emails me whenever doc build fails, and
for the past week or two, it has said the following:
```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 37 source files that are out of date
updating environment: 37 added, 0 changed, 0 removed
reading sources... [  2%] changelog
reading sources... [  5%] changelog_links
reading sources... [  8%] cli-reference
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/fpm/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
app.build(args.force_all, filenames)
[ ... …
```

Apply fix for readthedocs building errors.

---

.gitignore
CONTRIBUTORS
Dockerfile
Makefile
docs/docker.rst
spec/fpm/package/deb_spec.rb
spec/fpm/package/python_spec.rb
spec/fpm/package/snap_spec.rb

This changes the Dockerfile to create docker images suitable for running tests (fpm rspec suite in docker) and also as a normal release (using fpm through docker).
Fixes #1682, #1453
Fork of PR #1681 to resolve merge conflicts.

fpm tests can now be run through docker.

---

lib/fpm/package/empty.rb
spec/fpm/package/empty_spec.rb

This feels like the right default because empty packages have no files
(especially no binary, architecture-specific files) and therefore should
be installable on any architecture.
Fixes #1846

'empty' packages now default to "all" architecture.

---

lib/fpm/package/deb.rb

This should silence a warning in cases when packages do not contain any
/etc files. Prior to this commit, most debian package creation would
have this warning emitted:
```
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
```
Fixes #1851

Only show /etc "config files" warning when files are present in /etc.

---

lib/fpm/package/python.rb
spec/fixtures/python/setup.py
spec/fpm/package/python_spec.rb

This adds a new flag, --python-internal-pip, which is enabled by default.
"internal pip" means using 'python -m pip' to invoke pip. Ideally this will make fpm more correctly use pip.
Tested on python 2.7.17 and 3.6.9 on Ubuntu 18.04
All python tests passing 👍👍
Fixes #1820

By default, use pip for fetching and installing python packages.

---

lib/fpm/package/deb.rb
lib/fpm/package/rpm.rb
lib/fpm/package/virtualenv.rb

In #1854, it is reported that packaging fails. I think this happens because that specific use case invokes fpm via api and not via cli. When the cli is run, it loads all package type files. However, with the api, you `require()` your own files. 
I think files should require things they need, so this PR adds require() calls for places where  one package refers to another (like when converting things to deb). 
I used `grep FPM::Package:: lib/fpm/package/*.rb` to find cases where requires might be needed.
Test cases that failed without this PR:
```
% bundle exec ruby -r./lib/fpm/package/rpm.rb -e 'FPM::Package::RPM.new.tap { |x| x.name = "fancy" }.convert(FPM::Package::RPM)' 
% bundle exec ruby -r./lib/fpm/package/deb.rb -e 'FPM::Package::Deb.new.tap { |x| x.name = "fancy" …
```

Add missing requires to fix #1854 and fix breakage in 1.14.0 when using the fpm api.

---

fpm.gemspec

A prior commit removed `rake` as a development dependency on the
assumption that nothing in fpm's development process actually required
the use of `rake`.
However, I had forgotten about #756 (year 2014) which adds FPM::RakeTask
and some test coverage. FPM::RakeTask was added to allow folks to more
easily invoke FPM from within a Rake task.
At this time, I see no reason to remove FPM::RakeTask. Further, because
`rake` is typically (in my experience) used only in development
environments. Therefore, I believe the right solution is to restore
`rake` as a development_dependency in order to allow the test suite to
pass. For users of FPM::RakeTask, I would assume (hopefully correctly!)
that they already have `rake` installed as a dependency in their own
project, so the `fpm` gem has no need to …

Restore development_dependency on `rake`

---

lib/fpm/package/deb.rb

Previously, we would pass the literal `""` as an argument to `tar`.
`tar` would interpret this as a file name, which does not exist, and
fail.
This fixes the command to just pass no compression flag at all to tar
when `--deb-compression none` is set.
I did not add tests since I couldn't figure out how to execute them -
this is my first time working in ruby.

Fix `--deb-compression none`

---

lib/fpm/package/rpm.rb

Fixes the mangling FPM performs on the contents of RPM %files lists
to better match RPM's idiosyncratic filename handling.  FPM now
recognizes more cases that require special handling, and it
correctly distinguishes between the glob and non-glob cases,
which RPM itself treates differently.
Fixes #1385

Fix filename mangling for RPM targets

---

spec/fpm/package/rpm_spec.rb

Testing, this new test case fails on v1.14.1 and *succeeds* as expected
after #1882 was merged.
Fixes #1886

Add test case for files with spaces and quotatation marks.

---

lib/fpm/package/python.rb
spec/fpm/package/python_spec.rb

Previously, fpm would use `pip download ... --build ...` to instruct pip
to unpack a given python package to a specific directory for the purpose
of running something like `python setup.py` from it.
However, somewhere in 2021, pip removed this flag. First, I think, it
was deprecated and ignored, then finally removed. One reference to
this removal in the upstream pip project is this issue:
https://github.com/pypa/pip/issues/8333
Without `--build`, pip will place a single tarball in the destination
directory. Fpm cannot easily predict the name of this file because we
don't know the "real" name of the python package nor do we know the
version number being downloaded.
For example:
```
% python3 -m pip download --no-binary :all: --no-deps --no-clean django
...
Successfully downloaded django
% …
```

Run `pip` without the `--build` flag

---

lib/fpm/package.rb
lib/fpm/util.rb

* On Ruby 3.0.x and older, call ERB.new(template_code, nil, "-")
* On Ruby 3.1.0 and newer, call ERB.new(template_code, trim_mode: "-")
Fixes #1894

Call ERB.new correctly depending on the RUBY_VERSION

---

lib/fpm/package/deb.rb
spec/fpm/package/deb_spec.rb

Since Debian Policy version 4.0.1, the "extra" priority has been deprecated and replaced with "optional"; this triggers Lintian warnings for Debian packages built by FPM. Make this the new default for Debian package outputs when no value of `--deb-priority` is given.
Fixes #1398.

Change default Debian package priority to optional

---

templates/deb/changelog.erb
templates/deb/deb.changes.erb

In order to support packaging upload, the distribution must be set/aligned in changelog and changes files.
Required for example inside dput-ng repo upload app.

Replace whatever in changelog.erb and deb.changes.erb

---

lib/fpm/package/cpan.rb

This PR fixes issue #1523. 
Because [Class::Data::Inheritable](https://metacpan.org/release/TMTM/Class-Data-Inheritable-0.08) version 0.08 has a blank author field in its META.yml file, the bug can be reproduced with the following command:
```
fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir $HOME/fpm_tmp/ -s cpan -t rpm -v 0.08 Class::Data::Inheritable
```

Prevent crash if CPAN distribution has blank author field

---

spec/fpm/package/cpan_spec.rb

This PR adds a test to `cpan_spec.rb` for #1937.

Add test for CPAN dist with missing author

---

fpm.gemspec
lib/fpm/package/gem.rb

Folks are reporting that fpm cannot be installed easily (or at all) on older systems because a transitive dependency(1) rejects ruby versions older than 2.6.
(1) rubygem git depends on addressable which depends on public_suffix
Since the `git` dependency is only used in the `gem` source when using a git repo as a installation source, and that usage seems pretty simple -- clone a repo, checkout a branch, etc -- it feels safe to remove this dependency while still keeping the same functionality.
Fixes #1923

Remove `git` gem dependency.

---

lib/fpm/package/cpan.rb
spec/fpm/package/cpan_spec.rb

This PR fixes issue #1517 using the fix provided by #1518.
For handling CPAN tarballs with leading "./Foo/" directory structures, we must employ a tar `--transform` regex instead of a tar `--strip-components` command.
This bug can be reproduced by running the following command on the main branch:
```
fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir $HOME/tmp -t rpm -s cpan -v 0.010000 Alien::astyle
```
I also added a test to `cpan_spec.rb` that ensures Alien::astyle version 0.010000 can be built, but it should be noted that (on my machine) this tests causes the test suite to take about 4 minutes to run versus only about 30 seconds without this test.

CPAN support - Fix broken tar command

---

lib/fpm/util.rb

I believe you meant `stdin_w.close` but accidentally typed `stdin_w_close` in the `execmd` method.

Fixed bug in execmd: stdin_w_close -> stdin_w.close

---

fpm.gemspec
lib/fpm/package/osxpkg.rb
lib/fpm/util.rb

This change allows at least some of fpm to work under Ruby 1.9.3. I can produce rpms and debs using Ruby 1.9.3 and this patch! 
The `osxpkg` format doesn't seem to work for me on Ruby 1.9.3 because REXML seems to crash with an error.
This is accomplished by:
* removing the `json` dependency which has been included in Ruby by default since Ruby 1.9.1
* delaying rexml loading so that only uses that require xml parsing will load that library, such as osxpkg parsing.
* working around a frozen string modification error in `rubygems` under Ruby 1.9.3
You, reader, may be asking, "Why?"
In #1949, we discuss raising the minimum version of ruby required by fpm. At time of writing, the minimum version is set to '>= 1.9.3', and I'm somewhat slow to raise it without good cause.
Historically, there's …

JSON, REXML, and ruby 1.9.3 works again!

---

lib/fpm/package/osxpkg.rb

A user reported that on macOS Catalina, the default pkgbuild install
location may result in a .pkg file which cannot be installed.
This change makes fpm's `--prefix` option pass through to `pkgbuild`'s
`--install-location` flag
> With macOS Catalina, you can no longer store files or data in the read-only system volume, nor can you write to the "root" directory ( / ) from the command line, such as with Terminal.
References:
* macOS Catalina's new read-only root filesystem: https://support.apple.com/en-us/HT210650
Fixes #1908

Use pkgbuild's --install-location flag when fpm's --prefix is given.

---

lib/fpm/util.rb
spec/fpm/util_spec.rb

This PR fixes issue https://github.com/jordansissel/fpm/issues/1519 and https://github.com/jordansissel/fpm/issues/1522.
I based my fix off [this commit](https://github.com/jordansissel/fpm/pull/1610/commits/ae9594eb098f74c55166729d317d86af83e3b3f9) from https://github.com/jordansissel/fpm/pull/1610 that was never merged.
Because Inline::CPP version 0.80 has an interactive Makefile.PL, the bug can be reproduced by running the following command on the main branch (this command will hang):
```
fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir $HOME/tmp -t rpm -s cpan -v 0.80 Inline::CPP
```
Part of the issue in #1522 is that @wbraswell could not see the output from cpanminus, however this problem was fixed at some point. I added a test to `util_spec.rb` to ensure that …

Execmd: prevent prompting for input

---

lib/fpm/package/deb.rb

Debian policy is that package names may include a period, and this is used for a number of default packages (for instance, `ruby2.7`).
Binary package documentation points to the Source package docs:
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-package
Source package documentation includes ".":
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source
Current text: 
> Package names (both source and binary, see Package) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.
The regex in https://github.com/jordansissel/fpm/blob/788170598572ab2a9cb4d844575e3a9dab2ab467/lib/fpm/package/deb.rb#L41 
does not correctly …

[deb] The regex for valid package names in relationships does not allow names including "." (and is missing a couple of constraints)

---

lib/fpm/package/deb.rb
spec/fpm/package/deb_spec.rb

This fixes #1847 by adding an actionable error message when someone provides a version value that Debian's policy and tools will reject.
Includes test coverage :)

Reject invalid Debian version values.

---

lib/fpm/command.rb
lib/fpm/package/deb.rb
lib/fpm/package/dir.rb
lib/fpm/package/puppet.rb
lib/fpm/util.rb
spec/fpm/package/tar_spec.rb
spec/fpm/package/virtualenv_spec.rb

Ruby 3.2.0 was just released, and the deprecated methods `File.exists?` and `Dir.exists?` were completely removed. These methods are used in FPM, so FPM is currently broken under Ruby 3.2.0. Instead we are supposed to use the `File.exist?` and `Dir.exist?` methods. This PR replaces all occurrence of these deprecated methods with their preferred counterpart.

Replace deprecated {File,Dir}.exists? with {File,Dir}.exist?

---

lib/fpm/util.rb

Previously, fpm would write to the current directory when using methods to check for the correct `ar` and `tar` commands.
This now uses Stud::Temporary to get a random path in the system temporary directory.
I found this error in the test suite when the fpm git workspace was not writable -- for example, when mounted read-only through a container.
Error message, for posterity:
1) FPM::Command -p | --package when given a directory should write the package to the given directory.
Failure/Error: cmd.run(["-s", "empty", "-t", "deb", "-n", "example", "-p", path])
Errno::EACCES:
Permission denied @ rb_sysopen - fpm-dummy.tmp

Use a temporary path when testing archive commands.

---

spec/fpm/package/deb_spec.rb

This was a bug in the test suite.
```
1) FPM::Package::Deb#architecture should default to native
Failure/Error: expect(subject.architecture).to(be == expected)
expected: == "aarch64"
got:    "arm64"
```

Fix failing test when run on arm64/aarch64 systems 

---

lib/fpm/command.rb

This fixes fpm when used with clamp 1.3.0 or above.
Fixes #1543

Check if an option has a default value before we try to look it up.

---

fpm.gemspec

Ubuntu 22.04 LTS comes with ruby-clamp 1.1.1 which seems to work just
fine with fpm 1.15.1
Relaxing the version pin seems to be the right thing to do.

chore: relax 'clamp' version pin

---

docs/installation.rst

One character change!
I was reading the docs and noticed the link for ruby installation instructions was broken. This fixes it

fix the link to ruby installation instructions

---

lib/fpm/package/deb.rb

Before the change, when using an option --deb-systemd myunit.timer, the actual file created would be
/lib/systemd/system/myunit.timer.service
Because of that, systemd would then not find the timer.
With this change, the correct extension is extracted from the file, defaulting to .service.
Typically, there would be two files for installing a timer:
--deb-systemd myunit.service (where .service could be omitted) and --deb-systemd myunit.timer
So that the .timer references a .service file.
Fixes #1978

Add support for .timer units to --deb-systemd

---

docs/cli-reference.rst
docs/contributing.rst
docs/packages/cli/freebsd.rst
lib/fpm/package/freebsd.rb

- Sets (hardcodes) name of OS as `FreeBSD`
- Allows specifying the FreeBSD version the package is for, defaults to `13` and allows `all` or `noarch`.
- Correctly honors `--architecture` input.
- Fixes #1880
- Tested on Freebsd 13. Using `--architecture` as `12`, `13`, and `*`. 
- Using `12` correctly produces a wrong architecture message. 
- Using `13` and `*` work. Meaning `pkg add` does not return error.

Create FreeBSD packages with correct architecture

---

lib/fpm/package/deb.rb
spec/fpm/package/deb_spec.rb

This PR adds what it says on the tin to make fpm compatible with recent Debian and derivatives which implement zstd compression for their packages.
Fixes https://github.com/jordansissel/fpm/issues/2007.

Add support for zstd compression for deb packages.

---

lib/fpm/package/python.rb

It seems that `debugpy` on pip returns a `zip` file instead of a `tar.gz`

Support pip download returning a zip file

---

lib/fpm/package/deb.rb

This option will allow you to override the path within the staging directory systemd service files are moved to in debian packages.
On some systems systemd should not go in the hardcoded /lib/systemd/system but in /usr/lib/systemd/system instead. Many systems have the both symlinked, but not all so assuming /lib/systemd/system can be dangerous.

Add option --deb-systemd-path

---

lib/fpm/package/python.rb

Ran into an error creating a deb package from a python package when the current working directory contains spaces.
```
{:timestamp=>"2024-05-16T15:17:42.793044+0000", :message=>"Process failed: /bin/bash failed (exit code 127). Full command was:[\"/bin/bash\", \"-c\", \"env PYTHONPATH=/var/lib/jenkins-swarm-client/workspace/publiq packages/packages/vendor/bundle/ruby/2.7.0/gems/fpm-1.15.1/lib/fpm/package:$PYTHONPATH python3 setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build-627893c057255449a6af5622973a2c6df56cf6dde757466135f518e6bcdc/metadata.json\"]", :level=>:error}
```
The pylib variable gets passed to a shell command unescaped which causes the problem.
Adding a simple `.shellescape` solves the problem locally.

Escape the pylib path when using it in a shell command

---

lib/fpm/package/rpm.rb
spec/fpm/package/rpm_spec.rb
templates/rpm.erb

`rpmlint` considers a lack of a changelog an error.
this is a similar behaviour to the DEB packager, where a generic default changelog is generated unless one is provided explicitly.

rpm: generate changelog if none is provided

---

lib/fpm/package/deb.rb

Fix #2006
This was manually tested, but please let me know if you'd wish to add some automated tests. I'm very new to the ruby ecosystem so I'm a bit at lost :sweat_smile:

deb: add a --compression-level option

---

lib/fpm/package/rpm.rb

`perl` rpm package is a metapackages which install all the Perl bits and core modules
Then, `perl-devel`, `gcc` and lot of useless dependencies are installed
This should be replaced by `perl-interpreter`
<details>
<summary><i>perl dependencies</i></summary>
<pre><code>
Last metadata expiration check: 0:35:46 ago on Fri Sep  6 07:47:45 2024.
perl(:MODULE_COMPAT_5.32.1)
perl-Archive-Tar
perl-Attribute-Handlers
perl-AutoLoader
perl-AutoSplit
perl-B
perl-Benchmark
perl-CPAN
perl-CPAN-Meta
perl-CPAN-Meta-Requirements
perl-CPAN-Meta-YAML
perl-Carp
perl-Class-Struct
perl-Compress-Raw-Bzip2
perl-Compress-Raw-Zlib
perl-Config-Extensions
perl-Config-Perl-V
perl-DBM_Filter
perl-DB_File
perl-Data-Dumper
perl-Devel-PPPort
perl-Devel-Peek
perl-Devel-SelfStubber
perl-Digest
perl-Digest-MD5 …

fix(rpm): replace perl dependency by perl-interpreter

---

lib/fpm/package/deb.rb

When packaging a deb sometimes the architecture comes through as part of the provides (not sure why) but this causes problems with the deb package as it seems to only ever expect one set of round brackets which is the version indicator
Also fixed another issue where ppc64le packages from RPM wouldn't install properly on DEB based systems as they use ppc64el.
Also fixed another issue where invalid dependencies were being put in the control file (rpmlib dependencies and file path dependencies i.e. RPMs that depend on /bin/sh)
This has got fpm working for RPMs->DEBs on our systems for ppc64le packages. Appreciate that this fix might not be "complete" or comprehensive in any way, shape or form so any feedback is welcome.

Fix for #1627

---

lib/fpm/package/deb.rb

Small admendment to #2009 which makes zstd/deb tarfiles work on macOS

When using zstd, use tar flags that are compatible with both gnu tar and bsdtar (#2009)

---

lib/fpm/package/rpm.rb

The previous versions where all returning 404. This change points to the new correct locations.
(This is a rebase of #2011)

fix RPM documentation links in docs and code

---

lib/fpm/package/deb.rb

deb: A local path copied with --config-files should still be included in the package's conffiles list (Fixes #1823)
