- spec/fpm/package/deb_spec.rb
Over the years, I learn new things about rspec and I find ways of writing specs that feels better. This is step 1 of a long-needed upgrade to how rspec is used in fpm.
> Update rspec style

- CONTRIBUTORS
Hi there!
It's been really cool to see this project take off, and I'm really proud to be listed in CONTRIBUTORS.  I've had a name change since contributing, though, so I'd really love it if you could update that.
Thanks!
--Jeanine
> update name in CONTRIBUTORS

- lib/fpm/command.rb
This just fixes the issues comment on in pr #874
> fix typos in pr 874

- lib/fpm/command.rb
> fixed typo in command.rb

- lib/fpm/package/deb.rb
- spec/fpm/package/deb_spec.rb
> Fixed  deb_meta_file symbol name

- lib/fpm/package/rpm.rb
- spec/fpm/package/rpm_spec.rb
- templates/rpm.erb
This turned out a bit more complex than expected since defaulting to another attribute turns out to not actually work the way I thought it did. Feedback from maintainers would be good since I'm sure there's a better way to make this work in less code. Resolves #903.
> RPM summary

- lib/fpm/command.rb
seems slipped in from 9695ee06
> remove duplicate :architecture

- spec/fpm/package/sh_spec.rb
@jordansissel You said in #913 that you would like to see some specs for that PR, so I have gone back and made them. They pass and the thing works, hope this helps.
> Add specs for PR #913

- lib/fpm/package/rpm.rb
See https://github.com/jordansissel/fpm/issues/381#issuecomment-162644413
> Don't warn when RPM Epoch isn't set

- lib/fpm/package/deb.rb
:star2: Should fix https://github.com/itchio/itch/issues/93 :bug:
> deb: explicitly chmod triggers to 0644 for lintian

- lib/fpm/package/virtualenv.rb
Fix [issue#1055](https://github.com/jordansissel/fpm/issues/1055)
> File class do not have a world_readable function

- lib/fpm/package/deb.rb
> Drop duplicate .conf suffix

- lib/fpm/package/freebsd.rb
> Lazily require xz at the last possible moment to avoid dependency on liblzma.so.5

- README.md
Adding freebsd to the README due to recently introduced functionality.
> Update README.md with freebsd in the targets list

- .travis.yml
- lib/fpm/package/virtualenv.rb
Looks like #1124 broke some of the virtualenv features, this fixes that, plus another bug, and a blind attempt at getting travis to run the python virtualenv tests
> Bugfix virtualenv various

- lib/fpm/package/cpan.rb
- Added httppost function to cpan.rb
- Determine correct archive download URL using metacpan API search (using POST request). More reliable than previous GET method (see issue #1206).
> Fixes #1206 Improved download URL query for CPAN modules

- lib/fpm/util/tar_writer.rb
> Use StringIO from ruby stdlib

- examples/api/dir-to-deb-rpm-with-init.rb
Took me some time to figure out how to use the api -- So I am submitting this example to add some documentation for the API, specifically pleaserun.
> Add example: create rpm&deb packages with init scripts

- lib/fpm/package/apk.rb
This file is for Alpine packages, not Debian packages! 😄
> Fix comment in apk.rb

- lib/fpm/package/deb.rb
Fix issue 1212 https://github.com/jordansissel/fpm/issues/1212
> deb data file should support bz2 format

- lib/fpm/package/pleaserun.rb
Added support for --pleaserun-chdir to specify the working directory of a
created service.
> pleaserun: support chdir parameter

- docs/source/rpm.rst
Hey, this look like the sort of thing you're after?  If so, I can go and do this for a bunch of stuff I have some experience with.
> First stab at rpm docs

- docs/source/virtualenv.rst
- lib/fpm/package/virtualenv.rb
- spec/fpm/package/virtualenv_spec.rb
> Fix virtualenv prefix behaviour (#1248)

- lib/fpm/package/deb.rb
> fix wrong init.d shim naming

- lib/fpm/package/pleaserun.rb
Add all pleaserun options to be used with custom ruby script - like in examples/api/dir-to-deb-rpm-with-init.rb
> pleaserun: add extra options to pleaserun

- lib/fpm/package/dir.rb
> package/dir: remove spurious pry

- lib/fpm/package/deb.rb
- spec/fpm/package/deb_spec.rb
Added these two options to allow the debian functionalities associated with them
> Added --deb-interest-noawait and --deb-activate-noawait (#1225)

- README.rst
> Provide project-level badges in the README

- lib/fpm/package/pyfpm/get_metadata.py
- spec/fixtures/python/requirements.txt
- spec/fixtures/python/setup.py
- spec/fpm/package/python_spec.rb
Process PEP0508 markers on python package requirements
Closes-bug: #1307
> Process PEP0508 markers on python package requirements

- docs/source/virtualenv.rst
I just clicked the edit button on the readthedocs sites, so I apologize if this wasn't the correct way to make a PR for this site.
> Fixes typo; claims to make an rpm, but really deb

- fpm.gemspec
> Fix ruby-xz version

- lib/fpm/package/cpan.rb
Fixed https://github.com/jordansissel/fpm/pull/1510
> Perl CPAN Support, Fix Broken PERL5LIB & Add cpanm Verbose Option

- CHANGELOG.rst
- docs/changelog_links.rst
- lib/fpm/version.rb
@wbraswell found another bug while testing 1.10.1, so it's time for a quick patch to fix that :)
> Version bump to 1.10.2

- lib/fpm/package/deb.rb
> Auto-detects compression (if any) of elements of .deb packages.

- singularity.def
[Singularity](https://github.com/sylabs/singularity) is an opensource container platform widely used in EPC and HPC environments. 
I've been using it for some time already and becomes very interesting when someone needs to create packages in multiple different systems, without needing to install all dependencies every time.
This PR adds a definition file that can be used to build the container.
> Add Singularity definition file

- .travis.yml
- lib/fpm/package/gem.rb
- spec/fpm/package/cpan_spec.rb
- spec/fpm/package/python_spec.rb
- spec/fpm/package/rpm_spec.rb
- spec/fpm/package/snap_spec.rb
- spec/fpm/package_spec.rb
```
% bundle exec rspec
........................................................................................................................................................
................................................................................................................................
Finished in 22.03 seconds (files took 0.32223 seconds to load)
280 examples, 0 failures
```
It's been a long time since 100% of the specs have passed locally on my workstation. ;)
> Attempt to fix failing rspecs.

- lib/fpm/package/deb.rb
> Issue 1678

- lib/fpm/package/rpm.rb
https://github.com/jordansissel/fpm/issues/1675
The value can be a number from 0 to 9 inclusive. The default mirrors
the current behavior of 9. If the --rpm-compression value is set to
"none", this value is ignored.
Setting the value to 5 sped up RPM creation on my RPM from 9 to
3 minutes.
> Add a new --rpm-compression-level option which addresses issue 1675:

- Dockerfile
> Update Docker base image to Alpine 3.12

- lib/fpm/package/deb.rb
Fix for https://github.com/jordansissel/fpm/issues/1739
> Adds zlib requirements for deb packages

- lib/fpm/package/python.rb
Sometimes private devpi registry doesn't have a valid ssl-certificate, so pip is unable to install something from it. This patch adds option "--trusted-host" which allows work with unsecure devpi registies.
> Add trusted-host option for pip

- lib/fpm/package/deb.rb
- templates/deb/postinst_upgrade.sh.erb
- templates/deb/postrm_upgrade.sh.erb
- templates/deb/preinst_upgrade.sh.erb
- templates/deb/prerm_upgrade.sh.erb
Signed-off-by: Andreas Ulm <andreas.ulm@root360.de>
> added set -e to debian maintainer scripts #1696

- lib/fpm/package/gem.rb
On older rubies, YAML.load _is_ the unsafe load method. At some point,
Ruby 3.1.0 / Psych 4(?) made two renames:
* YAML.load -> YAML.unsafe_load
* YAML.safe_load -> YAML.load
A quick test is to try converting a gem. This would fail if `YAML.load`
was the "safe" method because it would fail with this message:
Tried to load unspecified class: Gem::Specification (Psych::DisallowedClass
`fpm -s gem -t empty rails` will crash on Ruby 3.1.0 prior to this
commit.
Fixes #1895
> Use YAML.unsafe_load on Ruby 3.1.0 and newer

- spec/fpm/package/deb_spec.rb
> Support newer version of lintian in the test suite.

- lib/fpm/command.rb
- spec/fpm/command_spec.rb
> Work-in-progress: Add new flag to allow reading additional options from a file.

- Dockerfile
- change base image to ubuntu:20.04
- support ruby 2.7
- docker lint
> chore: refactor Dockerfile

- lib/fpm/package/deb.rb
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
#1847
> Drop leading v from version for Debian

- .github/main.workflow
- .github/workflows/ruby.yml
- spec/fpm/package/osxpkg_spec.rb
- spec/fpm/package/virtualenv_spec.rb
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/gliptak/fpm/actions/runs/3611226074
After getting `virtual_spec.rb` green, `virtualenv` to be installed
> Update GHA build

- docs/packages/dir.rst
> Typo: Fix formatting for --prefix in dir.rst
